name: Rust Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust Validation
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ’¾ Check out files
      uses: actions/checkout@v4

    - name: ğŸ”¨ Build
      run: cargo build

    - name: ğŸ©º Run tests
      run: cargo test

    - name: ğŸ“ Run clippy
      run: cargo clippy

    - name: ğŸ” Check formatting
      run: cargo fmt --check
